---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/work/repo
    steps:
      - checkout
      - run: pip install ansible-lint --user
      - run: /home/circleci/.local/bin/ansible-lint ./*.yml
